apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapibri
spec:
  selector:
    matchLabels:
      app: pokeapibri
  template:
    metadata:
      labels:
        app: pokeapibri
    spec:
      containers:
      - name: pokeapibri
        image: sahat850/pokeapi:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Mi"
            cpu: "1m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        # livenessProbe:
        #   httpGet:
        #     path: "/v1/ping"
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   httpGet:
        #     path: "/v1/ping"
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
      # imagePullSecrets:
      #   - name: melissa-hol-group
---
apiVersion: v1
kind: Service
metadata:
  name: pokeapibri
spec:
  selector:
    app: pokeapibri
  ports:
  - port: 80
    targetPort: 8080
