apiVersion: apps/v1
kind: Deploy
metadata:
  labels:
    app: pokeapibri
  name: pokeapibri
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeapibri
  template:
    metadata:
      labels:
        app: pokeapibri
    spec:
      containers:
      
image: sahat850/pokeapi:latest
      name: pokeapibri
      ports:
containerPort: 8080
    resources:
      limits:
        cpu: "250m"
        memory: "250Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
  restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pokeapibri
  name: pokeapibri
spec:
  ports:
  
name: "pokeapi"
  port: 80
  targetPort: 8080
selector:
  app: pokeapi
type: LoadBalancer
